language: node_js
node_js:
  - "node"
  - "lts/*"
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database klein_test;' -U postgres
env:
  - DATABASE_URL=postgres://localhost:5432/klein_test?user=postgres